name: naan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.27646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4ce886'
    - '#1d1d1b'
    - '#41b86d'
    - '#378f57'
    - '#25412e'
  brandStrength: 0.75
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
